#!/usr/bin/python3

import subprocess
import shutil
import sys
import os

def enable_limited_access():
    try:
        shutil.copy('/etc/.nsswitch.conf.limited.internet.on', '/etc/nsswitch.conf')
        build_hosts()
        print("[+] limited internet = ON.")
        subprocess.call(['killall', 'firefox'])
    except PermissionError:
        print("[-] Permission denied. Try running with sudo.")
        sys.exit()

def disable_limited_access():
    try:
        shutil.copy('/etc/.nsswitch.conf.limited.internet.off', '/etc/nsswitch.conf')
        shutil.copy('/etc/.hosts.bak', '/etc/hosts')
        print("[+] limited internet = OFF.")
    except PermissionError:
        print("[-] Permission denied. Try running with sudo.")
        sys.exit() 

def refresh_nsswitch():
    subprocess.call(['sudo', 'systemctl', 'stop', 'nscd'])
    subprocess.call(['sudo', 'systemctl', 'stop', 'NetworkManager'])
    subprocess.call(['sudo', 'systemctl', 'start', 'nscd'])
    subprocess.call(['sudo', 'systemctl', 'start', 'NetworkManager'])

def init_config_files():
    if (not os.path.exists('/etc/.nsswitch.conf.limited.internet.on')):
        shutil.copy('/etc/nsswitch.conf', '/etc/.nsswitch.conf.limited.internet.on')
    if (not os.path.exists('/etc/.nsswitch.conf.limited.internet.off')):
        shutil.copy('/etc/nsswitch.conf', '/etc/.nsswitch.conf.limited.internet.off')

    if (not os.path.exists('/etc/.hosts.bak')):
        shutil.copy('/etc/hosts', '/etc/.hosts.bak')

def build_hosts():
    # start with a clean /etc/hosts and then build it from websites.txt
    shutil.copy('/etc/.hosts.bak', '/etc/hosts')

    try:
        websites_file = open(scriptdir  + '/websites.txt', 'rt')
        websites = websites_file.readlines()
    except FileNotFoundError:
        print("[-] Create a file called websites.txt on the directory you downloaded the script.")
        sys.exit()

    hosts_file = open('/etc/hosts', 'at')
    for line in websites:
        command = "nslookup " + line.strip() +  " | grep Address | head -2 | tail -1 | awk '{print $2}'"
        ip = subprocess.getoutput(command )
        hosts_file.write(ip)
        hosts_file.write('\t')
        hosts_file.write(line)

    hosts_file.close()
    websites_file.close()

def append_other_entries(option):
    input_file_name = 'other_' + option + '.txt' 
    input_file_name_full = scriptdir + '/' + input_file_name
    if  os.path.exists(input_file_name_full):
        input_file = open(input_file_name_full)
        entries = input_file.read()

        hosts_file = open('/etc/hosts', 'at')
        hosts_file.write(entries)

        hosts_file.close()
        input_file.close()




scriptdir = os.path.abspath(os.path.dirname(sys.argv[0]))
option = sys.argv[1]


if option=='on':
    enable_limited_access()
elif option == 'off':
    disable_limited_access()

append_other_entries(option)
refresh_nsswitch()
